"""Add Session table

Revision ID: 4027fdde410e
Revises: 66ce085a374d
Create Date: 2026-03-23 00:07:21.000916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4027fdde410e'
down_revision: Union[str, None] = '66ce085a374d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Session',
    sa.Column('id', sa.Text(), server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('refreshToken', sa.Text(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refreshToken')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Session')
    # ### end Alembic commands ###
