"""init_chat_schema_with_constraints

Revision ID: 66ce085a374d
Revises: 
Create Date: 2026-03-13 23:55:41.117795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ce085a374d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Text(), server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('hashedPassword', sa.Text(), nullable=False),
    sa.Column('displayName', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('avatarUrl', sa.Text(), nullable=True),
    sa.Column('avatarId', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Conversation',
    sa.Column('id', sa.Text(), server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'), nullable=False),
    sa.Column('type', sa.Enum('direct', 'group', name='conversation_type'), nullable=False),
    sa.Column('groupName', sa.Text(), nullable=True),
    sa.Column('groupCreatedBy', sa.Text(), nullable=True),
    sa.Column('lastMessageContent', sa.Text(), nullable=True),
    sa.Column('lastMessageCreatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lastMessageSender', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(type = \'group\') OR (type = \'direct\' AND "groupName" IS NULL AND "groupCreatedBy" IS NULL)', name='check_group_fields_conditional'),
    sa.ForeignKeyConstraint(['groupCreatedBy'], ['User.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lastMessageSender'], ['User.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_type', 'Conversation', ['type'], unique=False)
    op.create_table('Friend',
    sa.Column('id', sa.Text(), server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'), nullable=False),
    sa.Column('userA', sa.Text(), nullable=False),
    sa.Column('userB', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"userA" <> "userB"', name='no_self_friendship'),
    sa.ForeignKeyConstraint(['userA'], ['User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userB'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userA', 'userB', name='unique_friendship')
    )
    op.create_index('idx_friend_userA', 'Friend', ['userA'], unique=False)
    op.create_index('idx_friend_userB', 'Friend', ['userB'], unique=False)
    op.create_table('FriendRequest',
    sa.Column('id', sa.Text(), server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'), nullable=False),
    sa.Column('from', sa.Text(), nullable=False),
    sa.Column('to', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"from" <> "to"', name='no_self_request'),
    sa.ForeignKeyConstraint(['from'], ['User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from', 'to', name='unique_friend_request')
    )
    op.create_index('idx_friendrequest_from', 'FriendRequest', ['from'], unique=False)
    op.create_index('idx_friendrequest_to', 'FriendRequest', ['to'], unique=False)
    op.create_table('ConversationParticipant',
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('conversationId', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['conversationId'], ['Conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'conversationId')
    )
    op.create_index('idx_participant_conv', 'ConversationParticipant', ['conversationId'], unique=False)
    op.create_index('idx_participant_user', 'ConversationParticipant', ['userId'], unique=False)
    op.create_table('ConversationSeenBy',
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('conversationId', sa.Text(), nullable=False),
    sa.Column('seenAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversationId'], ['Conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'conversationId')
    )
    op.create_index('idx_seenby_conv', 'ConversationSeenBy', ['conversationId'], unique=False)
    op.create_index('idx_seenby_user', 'ConversationSeenBy', ['userId'], unique=False)
    op.create_table('Message',
    sa.Column('id', sa.Text(), server_default=sa.text('CAST(gen_random_uuid() AS TEXT)'), nullable=False),
    sa.Column('senderId', sa.Text(), nullable=False),
    sa.Column('conversationId', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('imgUrl', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('content IS NOT NULL OR "imgUrl" IS NOT NULL', name='message_has_content'),
    sa.ForeignKeyConstraint(['conversationId'], ['Conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senderId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_conversation', 'Message', ['conversationId', 'createdAt'], unique=False)
    op.create_index('idx_message_sender', 'Message', ['senderId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_message_sender', table_name='Message')
    op.drop_index('idx_message_conversation', table_name='Message')
    op.drop_table('Message')
    op.drop_index('idx_seenby_user', table_name='ConversationSeenBy')
    op.drop_index('idx_seenby_conv', table_name='ConversationSeenBy')
    op.drop_table('ConversationSeenBy')
    op.drop_index('idx_participant_user', table_name='ConversationParticipant')
    op.drop_index('idx_participant_conv', table_name='ConversationParticipant')
    op.drop_table('ConversationParticipant')
    op.drop_index('idx_friendrequest_to', table_name='FriendRequest')
    op.drop_index('idx_friendrequest_from', table_name='FriendRequest')
    op.drop_table('FriendRequest')
    op.drop_index('idx_friend_userB', table_name='Friend')
    op.drop_index('idx_friend_userA', table_name='Friend')
    op.drop_table('Friend')
    op.drop_index('idx_conversation_type', table_name='Conversation')
    op.drop_table('Conversation')
    op.drop_table('User')
    # ### end Alembic commands ###
