"""fix message content constraint

Revision ID: 8901234567ab
Revises: 6789012345ab
Create Date: 2026-03-31 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8901234567ab'
down_revision: Union[str, None] = '6789012345ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_has_content', 'Message', type_='check')
    op.create_check_constraint(
        'message_has_content',
        'Message',
        'is_deleted OR content IS NOT NULL OR "imgUrl" IS NOT NULL OR "fileUrl" IS NOT NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_has_content', 'Message', type_='check')
    op.create_check_constraint(
        'message_has_content',
        'Message',
        'is_deleted OR content IS NOT NULL OR "imgUrl" IS NOT NULL'
    )
    # ### end Alembic commands ###
